language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.0
          env: SYMFONY_ENV="3.3.*"
        - php: 7.1
          env: SYMFONY_ENV="3.3.*"
        - php: 7.2
          env: SYMFONY_ENV="3.3.*"
        - php: 7.0
          env: SYMFONY_ENV="3.4.*"
        - php: 7.1
          env: SYMFONY_ENV="3.4.*"
        - php: 7.2
          env: SYMFONY_ENV="3.4.*"
        - php: 7.1
          env: SYMFONY_ENV="4.0.*"
        - php: 7.2
          env: SYMFONY_ENV="4.0.*"

before_install:
  - travis_retry composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install:
  - composer require "symfony/symfony:${SYMFONY_ENV}" --no-update
  - composer update --prefer-dist --no-progress --no-suggest ${COMPOSER_FLAGS} --no-interaction

script:
  - $TEST_COMMAND

after_success:
  - if [[ "$COVERAGE" = true ]]; then pip install --user codecov && codecov ; fi
